name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ScriptAnalyzer with custom rules
        shell: pwsh
        run: |

          # Path to your custom rules
          $customRulePath = Join-Path $PWD ".rules"

          Write-Host "Using custom rules from: $customRulePath"
          Write-Host "Current directory: $PWD"

          # Analyze repository
          invoke-ScriptAnalyzer -Path $PWD -CustomRulePath $customRulePath\Check_For_SnakeCase.psm1

          # Output results
          if ($results) {
              $results | Format-Table

              Write-Error "PSScriptAnalyzer found violations."
              exit 1
          }

          Write-Host "No ScriptAnalyzer issues found."